import { ScrollView } from "std-widgets.slint";
import { MaterialRow } from "../components/material-row.slint";
import { CoursesUi, UiState } from "../globals.slint";
import { CourseTab, MaterialItem } from "../types/course-ui.slint";

export component MaterialSidebar inherits Rectangle {
    in property <CourseTab> tab;
    in property <[MaterialItem]> items: tab.parent-materials;
    in property <string> selected-id: tab.folder-id;

    width: 200px;
    background: {
        let c = UiState.theme.background-800.to-oklch();
        oklch(c.lightness - 0.03, c.chroma, c.hue, c.alpha)
    };
    VerticalLayout {
        padding-top: 16px;
        padding-bottom: 16px;
        padding-left: 8px;
        padding-right: 8px;
        spacing: 8px;
        sidebar := ScrollView {
            horizontal-scrollbar-policy: always-off;
            VerticalLayout {
                spacing: 2px;
                for item[i] in root.items: VerticalLayout {
                    padding-bottom: 2px;
                    MaterialRow {
                        width: sidebar.visible-width;
                        item: item;
                        selected: item.course-id == root.tab.course-id
                            && (item.kind == "course" || item.id == root.selected-id);
                    }
                }
            }
        }
    }
}
