import { Button } from "std-widgets.slint";

// touch area supports hover and button supports focus; this combines both to support both
export component HoverableButton inherits Rectangle {
    in property <string> text;
    in property <bool> enabled: true;
    out property <bool> has-hover: hover.has-hover;
    out property <bool> has-focus: button.has-focus;
    out property <bool> pressed: button.pressed;
    callback clicked();
    forward-focus: button;

    hover := TouchArea {
        enabled: root.enabled;
        mouse-cursor: root.enabled ? pointer : default;
        button := Button {
            width: 100%;
            height: 100%;
            opacity: 0;
            text: root.text;
            enabled: root.enabled;
            clicked => { root.clicked(); }
        }

        @children
    }
}
