import { UiState } from "../globals.slint";
import { TopBarFrame } from "top-bar-frame.slint";

export component ScreenTopBar inherits TopBarFrame {
    in property <string> title;
    in property <image> icon;

    HorizontalLayout {
        padding-left: 0.75rem;
        padding-right: 0.75rem;
        spacing: 0.375rem;
        alignment: start;

        VerticalLayout {
            alignment: center;
            Image {
                width: 0.875rem;
                height: 0.875rem;
                source: root.icon;
                colorize: oklch(0.65323, 0.06856, 57.29578, 1.0);
            }
        }

        Text {
            text: root.title;
            color: UiState.theme.text-200;
            font-size: 0.75rem;
            vertical-alignment: center;
        }

        @children
    }
}
