import { UiState } from "../globals.slint";
import { TopBarFrame } from "top-bar-frame.slint";

export component ScreenTopBar inherits TopBarFrame {
    in property <string> title;
    in property <image> icon;

    HorizontalLayout {
        padding-left: 12px;
        padding-right: 12px;
        spacing: 6px;
        alignment: start;

        VerticalLayout {
            alignment: center;
            Image {
                width: 14px;
                height: 14px;
                source: root.icon;
                colorize: oklch(0.65323, 0.06856, 57.29578, 1.0);
            }
        }

        Text {
            text: root.title;
            color: UiState.theme.text-200;
            font-size: 12px;
            vertical-alignment: center;
        }

        @children
    }
}
