import { HoverableButton } from "hoverable-button.slint";
import { UiState } from "../globals.slint";

export component SelectedItemAction {
    in property <string> hotkey-name;
    in property <string> action-name;
    in property <keys> hotkey;
    callback action();

    Rectangle {
        action-button := HoverableButton {
            text: root.action-name;
            clicked => { root.action(); }
        }

        Rectangle {
            border-radius: 5px;
            background: {
                let hoverBg = UiState.theme.background-600.to-oklch();
                action-button.has-hover || action-button.has-focus ? oklch(hoverBg.lightness, hoverBg.chroma, hoverBg.hue, 0.6) : transparent
            };
            vl := VerticalLayout {
                alignment: center;

                padding-left: 16px;
                padding-right: 16px;
                HorizontalLayout {
                    alignment: center;
                    spacing: 10px;
                    Rectangle {
                        border-width: 1px;
                        border-radius: 5px;
                        border-color: UiState.theme.background-600;
                        VerticalLayout {
                            padding-top: 1px;
                            padding-bottom: 1px;
                            padding-left: 5px;
                            padding-right: 5px;

                            Text {
                                text: hotkey-name;
                                font-size: 10px;
                                font-weight: 700;
                            }
                        }
                    }

                    Rectangle {
                        Text {
                            text: action-name;
                            font-size: 12px;
                        }
                    }
                }
            }
        }
    }
}
