import { VerticalBox, ScrollView } from "std-widgets.slint";
import { HoverableButton } from "hoverable-button.slint";
import { ProgressRing } from "progress-ring.slint";
import { Screen } from "../types/screen.slint";
import { UiState, NotificationUi, CoursesUi } from "../globals.slint";
import { Materials } from "materials/materials.slint";

component NavigationItem inherits Rectangle {
    in property <string> label;
    in property <image> icon;
    in property <int> item-index;
    in property <string> shortcut;
    in property <int> focus-request: -1;
    changed focus-request => { if root.focus-request == root.item-index { action.focus(); } }

    in property <Screen> change-to;
    in property <float> progress: 0;

    height: 44px;
    border-radius: 6px;
    background: UiState.screen == change-to ? UiState.theme.background-700 : (action.has-hover || action.has-focus ? UiState.theme.background-600 : transparent);

    action := HoverableButton {
        text: root.label;
        changed has-focus => {
            if self.has-focus { UiState.focused-sidebar-item = root.item-index; }
            else if UiState.focused-sidebar-item == root.item-index { UiState.focused-sidebar-item = -1; }
        }
        clicked => { UiState.screen = change-to; }
        Tooltip {
            VerticalLayout {
                padding: 4px;
                Text {
                    text: root.label;
                    color: UiState.theme.text-50;
                }

                Text {
                    text: UiState.shortcut-modifier + "+" + root.shortcut;
                    color: UiState.theme.text-200;
                }
            }
        }
    }

    if progress > 0: ProgressRing {
        progress: root.progress;
    }

    Image {
        source: icon;
        colorize: UiState.theme.text-200;
    }
    // Text {
    //     text: root.label;
    //     color: selected ? UiState.theme.text-50 : UiState.theme.text-200;
    //     font-size: 16px;
    //     vertical-alignment: center;
    //     x: 16px;
    // }
}

export component Sidebar inherits Rectangle {
    in property <int> focus-request: -1;
    in property <bool> minimized: true;

    width: minimized ? 60px : 240px;
    background: UiState.theme.background-900;

    VerticalLayout {
        padding-left: 8px;
        padding-right: 8px;
        padding-bottom: 4px;
        spacing: 10px;

        Rectangle {
            height: 0px;
        }

        NavigationItem {
            label: "Calendar";
            item-index: 0;
            focus-request: root.focus-request;
            shortcut: "1";
            icon: @image-url("../icons/calendar-days.svg");
            change-to: dashboard;
        }

        NavigationItem {
            label: "Notifications";
            item-index: 1;
            focus-request: root.focus-request;
            shortcut: "2";
            icon: @image-url("../icons/bell.svg");
            progress: NotificationUi.progress;
            change-to: notifs;
        }

        NavigationItem {
            label: "Courses";
            item-index: 2;
            focus-request: root.focus-request;
            shortcut: "3";
            icon: @image-url("../icons/book-text.svg");
            change-to: courses;
        }

        Rectangle {
            border-width: 1px;
            border-color: UiState.theme.background-700;
            height: 1px;
        }

        tabs := ScrollView {
            vertical-stretch: 1;
            horizontal-scrollbar-policy: always-off;
            VerticalLayout {
                spacing: 8px;
                alignment: start;
                for tab[index] in CoursesUi.tabs: Rectangle {
                    property <int> focus-request: root.focus-request;
                    changed focus-request => { if self.focus-request == index + 3 { tab-action.focus(); } }
                    width: tabs.visible-width;
                    height: 44px;
                    border-radius: 6px;
                    background: (UiState.screen == Screen.materials || UiState.screen == Screen.assignment) && CoursesUi.active-tab == index
                        ? UiState.theme.background-700
                        : tab-action.has-hover || tab-action.has-focus ? UiState.theme.background-600 : transparent;
                    accessible-role: button;
                    accessible-label: tab.title;
                    Rectangle {
                        width: 30px;
                        height: 30px;
                        x: (parent.width - self.width) / 2;
                        y: (parent.height - self.height) / 2;
                        border-radius: 15px;
                        background: oklch(0.7941, 0.04, 28.31, 1);
                        clip: true;
                        Image {
                            source: tab.image;
                            visible: !UiState.shift-held || !tab-action.has-hover;
                            width: parent.width;
                            height: parent.height;
                        }

                        if tab.image.width == 0 && (!UiState.shift-held || !tab-action.has-hover): Text {
                            text: tab.title;
                            width: parent.width - 8px;
                            x: 4px;
                            height: parent.height;
                            overflow: elide;
                            horizontal-alignment: center;
                            vertical-alignment: center;
                            color: UiState.theme.text-50;
                        }
                        if UiState.shift-held && tab-action.has-hover: Image {
                            source: @image-url("../icons/x.svg");
                            colorize: oklch(0.7903, 0.0986, 28.31, 1);
                            width: parent.width;
                            height: parent.height;
                        }
                    }

                    tab-action := HoverableButton {
                        text: tab.title;
                        changed has-focus => {
                            if self.has-focus { UiState.focused-sidebar-item = index + 3; }
                            else if UiState.focused-sidebar-item == index + 3 { UiState.focused-sidebar-item = -1; }
                        }
                        clicked => {
                            if UiState.shift-held { CoursesUi.close-tab(index); }
                            else { CoursesUi.select-tab(index); }
                        }
                        Tooltip {
                            VerticalLayout {
                                padding: 4px;
                                Text {
                                    text: tab.title;
                                    color: UiState.theme.text-50;
                                }

                                Text {
                                    text: UiState.shortcut-modifier + "+" + (index + 4);
                                    color: UiState.theme.text-400;
                                }
                            }
                        }
                    }
                }
            }
        }

        NavigationItem {
            label: "Settings";
            item-index: CoursesUi.tabs.length + 3;
            focus-request: root.focus-request;
            icon: @image-url("../icons/settings.svg");
            change-to: settings;
        }
    }
}
