import { VerticalBox, ScrollView } from "std-widgets.slint";
import { HoverableButton } from "hoverable-button.slint";
import { ProgressRing } from "progress-ring.slint";
import { Screen } from "../types/screen.slint";
import { UiState, NotificationUi, CoursesUi } from "../globals.slint";
import { Materials } from "materials/materials.slint";

component NavigationItem inherits Rectangle {
    in property <string> label;
    in property <image> icon;

    in property <Screen> change-to;
    in property <float> progress: 0;

    height: 44px;
    border-radius: 6px;
    background: UiState.screen == change-to ? UiState.theme.background-700 : (action.has-hover || action.has-focus ? UiState.theme.background-600 : transparent);

    action := HoverableButton {
        text: root.label;
        clicked => { UiState.screen = change-to; }
    }

    if progress > 0: ProgressRing {
        progress: root.progress;
    }

    Image {
        source: icon;
        colorize: UiState.theme.text-200;
    }
    // Text {
    //     text: root.label;
    //     color: selected ? UiState.theme.text-50 : UiState.theme.text-200;
    //     font-size: 16px;
    //     vertical-alignment: center;
    //     x: 16px;
    // }
}

export component Sidebar inherits Rectangle {
    in property <bool> minimized: true;

    width: minimized ? 60px : 240px;
    background: UiState.theme.background-900;

    VerticalBox {
        padding: 8px;
        spacing: 10px;

        Rectangle {
            height: 0px;
        }

        NavigationItem {
            label: "Dashboard";
            icon: @image-url("../icons/calendar-days.svg");
            change-to: dashboard;
        }

        NavigationItem {
            label: "Notifications";
            icon: @image-url("../icons/bell.svg");
            progress: NotificationUi.progress;
            change-to: notifs;
        }

        NavigationItem {
            label: "Courses";
            icon: @image-url("../icons/book-text.svg");
            change-to: courses;
        }

        Rectangle {
            border-width: 1px;
            border-color: UiState.theme.background-700;
            height: 1px;
        }

        tabs := ScrollView {
            vertical-stretch: 1;
            horizontal-scrollbar-policy: always-off;
            VerticalLayout {
                spacing: 8px;
                alignment: start;
                for tab[index] in CoursesUi.tabs: Rectangle {
                    width: tabs.visible-width;
                    height: 44px;
                    border-radius: 6px;
                    background: (UiState.screen == Screen.materials || UiState.screen == Screen.assignment) && CoursesUi.active-tab == index
                        ? UiState.theme.background-700
                        : tab-action.has-hover || tab-action.has-focus ? UiState.theme.background-600 : transparent;
                    accessible-role: button;
                    accessible-label: tab.title;
                    Rectangle {
                        width: 30px;
                        height: 30px;
                        x: (parent.width - self.width) / 2;
                        y: (parent.height - self.height) / 2;
                        border-radius: 15px;
                        background: UiState.theme.background-400;
                        Text {
                            text: tab.title;
                            width: parent.width - 8px;
                            x: 4px;
                            height: parent.height;
                            overflow: elide;
                            horizontal-alignment: center;
                            vertical-alignment: center;
                            color: UiState.theme.text-50;
                        }
                    }

                    tab-action := HoverableButton {
                        text: tab.title;
                        clicked => { CoursesUi.select-tab(index); }
                    }
                }
            }
        }

        NavigationItem {
            label: "Settings";
            icon: @image-url("../icons/settings.svg");
            change-to: settings;
        }
    }
}
