import { VerticalBox } from "std-widgets.slint";
import { ProgressRing } from "progress-ring.slint";
import { Screen } from "../screen/screens.slint";
import { UiState, NotificationUi } from "../globals.slint";

component NavigationItem inherits Rectangle {
    in property <string> label;
    in property <image> icon;

    in property <Screen> change-to;
    in property <float> progress: 0;

    height: 44px;
    border-radius: 6px;
    background: UiState.screen == change-to ? UiState.theme.background-700 : (touch.has-hover ? UiState.theme.background-600 : transparent);

    touch := TouchArea {
        pointer-event(event) => {
            if event.kind == PointerEventKind.down {
                UiState.screen = change-to;
            }
        }
    }

    if progress > 0: ProgressRing {
        progress: root.progress;
    }

    Image {
        source: icon;
        colorize: UiState.theme.text-200;
    }
    // Text {
    //     text: root.label;
    //     color: selected ? UiState.theme.text-50 : UiState.theme.text-200;
    //     font-size: 16px;
    //     vertical-alignment: center;
    //     x: 16px;
    // }
}

    export component Sidebar inherits Rectangle {
    in property <bool> minimized: true;

    width: minimized ? 60px : 240px;
    background: UiState.theme.background-900;

    VerticalBox {
        padding: 8px;
        spacing: 10px;

        Rectangle {
            height: 0px;
        }

        NavigationItem {
            label: "Dashboard";
            icon: @image-url("../icons/calendar-days.svg");
            change-to: dashboard;
        }

        NavigationItem {
            label: "Notifications";
            icon: @image-url("../icons/bell.svg");
            progress: NotificationUi.progress;
            change-to: notifs;
        }

        NavigationItem {
            label: "Courses";
            icon: @image-url("../icons/book-text.svg");
            change-to: courses;
        }

        Rectangle {
            border-width: 1px;
            border-color: UiState.theme.background-700;
            height: 1px;
        }

        Rectangle {
            vertical-stretch: 1;
        }

        NavigationItem {
            label: "Settings";
            icon: @image-url("../icons/settings.svg");
            change-to: settings;
        }
    }
}
