import { CoursesUi, UiState } from "../../globals.slint";
import { MaterialItem, CourseTab } from "../../types/course-ui.slint";
import { MaterialIcon } from "material-icon.slint";

export component MaterialRow inherits Rectangle {
    in property <MaterialItem> item;
    in property <bool> selected;
    in property <float> tint;

    private property <bool> navigable: item.kind == "folder" || item.kind == "course";
    height: 40px;
    border-radius: 5px;
    background: (selected ? UiState.theme.background-600
        : touch.has-hover ? UiState.theme.background-700 : transparent);
    HorizontalLayout {
        padding-left: 12px;
        padding-right: 12px;
        spacing: 10px;
        VerticalLayout {
            alignment: center;
            MaterialIcon {
                width: 20px;
                height: 20px;
                kind: item.kind;
            }
        }

        Text {
            text: item.title;
            color: UiState.theme.text-50;
            vertical-alignment: center;
            overflow: elide;
            font-size: 18px;
            horizontal-stretch: 1;
        }

        Text {
            text: root.navigable ? "›" : "";
            color: UiState.theme.text-200;
            vertical-alignment: center;
        }
    }

    touch := TouchArea {
        mouse-cursor: pointer;
        clicked => {
            if root.navigable {
                CoursesUi.navigate-folder(item.course-id, item.id);
            }
            if item.kind == "assignment" {
                CoursesUi.navigate-assignment(item.course-id, item.id);
            }
        }
    }
}
