import { UiState } from "../../globals.slint";
import { MaterialIcon } from "material-icon.slint";
import { HoverableButton } from "../hoverable-button.slint";

export component MaterialBreadcrumb inherits Rectangle {
    in property <string> title;
    in property <string> kind;
    callback activated();
    height: 32px;
    background: action.has-hover || action.has-focus ? UiState.theme.background-700 : transparent;
    border-radius: 4px;
    accessible-role: button;
    accessible-label: title;
    HorizontalLayout {
        spacing: 6px;
        alignment: center;
        VerticalLayout {
            alignment: center;
            MaterialIcon {
                width: 16px;
                height: 16px;
                kind: root.kind;
            }
        }

        Text {
            text: root.title;
            color: UiState.theme.text-200;
            font-size: 12px;
            vertical-alignment: center;
        }
    }

    action := HoverableButton {
        text: root.title;
        clicked => { root.activated(); }
    }
}
