import {
    HorizontalBox,
    VerticalBox,
    ScrollView,
    ListView,
} from "std-widgets.slint";
import { Theme } from "../palette.slint";
import { UiState, DashboardUi } from "../globals.slint";

export component SelectedItemAction {
    in property <string> hotkey-name;
    in property <string> action-name;
    in property <keys> hotkey;
    callback action();

    touch := TouchArea {
        clicked => {
            action();
        };
        Rectangle {
            border-radius: 5px;
            background: {
                let hoverBg = UiState.theme.background-600.to-oklch();
                touch.has-hover ? oklch(hoverBg.lightness, hoverBg.chroma, hoverBg.hue, 0.6) : transparent
            };
            vl := VerticalLayout {
                alignment: center;

                padding-left: 16px;
                padding-right: 16px;
                HorizontalLayout {
                    alignment: center;
                    spacing: 10px;
                    Rectangle {
                        border-width: 1px;
                        border-radius: 5px;
                        border-color: UiState.theme.background-600;
                        VerticalLayout {
                            padding-top: 2px;
                            padding-bottom: 2px;
                            padding-left: 6px;
                            padding-right: 6px;

                            Text {
                                text: hotkey-name;
                                font-size: 12px;
                                font-weight: 700;
                            }
                        }
                    }

                    Rectangle {
                        Text {
                            text: action-name;
                            font-size: 12px;
                        }
                    }
                }
            }
        }
    }
}

export component Dashboard inherits Rectangle {
    background: UiState.theme.background-800;
    vertical-stretch: 1;

    VerticalLayout {
        vertical-stretch: 1;
        HorizontalBox {
            for col[x] in DashboardUi.assignment-view: VerticalBox {
                alignment: stretch;
                vertical-stretch: 1;

                Text {
                    text: col.title;
                    horizontal-alignment: center;
                }

                Rectangle {
                    background: UiState.theme.background-750;
                    ListView {
                        vertical-stretch: 1;
                        horizontal-scrollbar-policy: always-off;
                        for assignment[y] in col.assignments: Rectangle {
                            height: inner.height + 8px;
                            touch := TouchArea {
                                clicked => {
                                    DashboardUi.selected-assignment = assignment;
                                    DashboardUi.sel-col = x;
                                    DashboardUi.sel-row = y;
                                }
                                inner := Rectangle {
                                    background: {
                                        let c = (assignment.done ? oklch(0.55447, 0.08888, 153.33561, 1.0) :
                                            (assignment.overdue ? oklch(0.50323, 0.06856, 57.29578, 1.0) :
                                            oklch(0.46882, 0.06986, 263.55386, 1.0))).to-oklch();
                                        let selected = DashboardUi.selected-assignment.id == assignment.id;

                                        oklch(
                                    c.lightness + (touch.has-hover ? 0.1 : 0) + (selected ? 0.2 : 0),
                                    c.chroma + (touch.has-hover ? 0.02 : 0) + (selected ? 0.06 : 0),
                                    c.hue,
                                    c.alpha)
                                    };
                                    animate background { duration: 50ms; }
                                    border-radius: 5px;
                                    height: min(120px, max(40px, self.preferred-height));
                            // Text measurements include font size, weight, and wrapping.
                            preferred-height: title.preferred-height + course.preferred-height
                                        + content.padding-top + content.padding-bottom + 16px;
                                    clip: true;

                                    content := VerticalBox {
                                        spacing: 2px;
                                        title := Text {
                                            text: assignment.title;
                                            font-weight: 700;
                                            wrap: word-wrap;
                                        }

                                        course := Text {
                                            color: UiState.theme.text-400;
                                            text: assignment.course-name;
                                            wrap: word-wrap;
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }

        Rectangle {
            background: {
                let c = UiState.theme.background-800.to-oklch();
                oklch(c.lightness - 0.05, c.chroma, c.hue, c.alpha);
            }
            height: 32px;
            if !DashboardUi.selected-assignment.course-id.is-empty: focus := FocusScope {
                init => { focus.focus() }
                KeyBinding {
                    keys: view-item.hotkey;
                    activated => { view-item.action() }
                }

                KeyBinding {
                    keys: mark-done.hotkey;
                    activated => { mark-done.action() }
                }

                KeyBinding {
                    keys: unselect.hotkey;
                    activated => { unselect.action() }
                }

                HorizontalLayout {
                    alignment: center;
                    view-item := SelectedItemAction {
                        hotkey-name: "V";
                        hotkey: @keys(V);
                        action-name: "View item";
                        action => { DashboardUi.view-item(); }
                    }

                    mark-done := SelectedItemAction {
                        hotkey-name: "D";
                        hotkey: @keys(D);
                        action-name: DashboardUi.selected-assignment.done ? "Unmark as done" : "Mark as done";
                        action => {
                            DashboardUi.assignment-view[DashboardUi.sel-col].assignments[DashboardUi.sel-row].done = !DashboardUi.selected-assignment.done;
                            DashboardUi.selected-assignment = DashboardUi.assignment-view[DashboardUi.sel-col].assignments[DashboardUi.sel-row];
                            DashboardUi.set-done(DashboardUi.selected-assignment.done, DashboardUi.selected-assignment.id);
                        }
                    }

                    unselect := SelectedItemAction {
                        hotkey-name: "Esc";
                        hotkey: @keys(Escape);
                        action-name: "Unselect item";
                        action => {
                            DashboardUi.selected-assignment = { };
                        }
                    }
                }
            }
        }
    }
}
