import { ScrollView } from "std-widgets.slint";
import { Screen } from "screens.slint";
import { MaterialRow } from "../components/material-row.slint";
import { MaterialItem, CourseTab } from "../types/course-ui.slint";
import { MaterialBreadcrumb } from "../components/material-breadcrumb.slint";
import { MaterialSidebar } from "../components/course-sidebar.slint";
import { UiState, CoursesUi } from "../globals.slint";
import { Theme } from "../palette.slint";

export component Materials inherits Rectangle {
    in property <CourseTab> tab;
    VerticalLayout {
        spacing: 0px;
        HorizontalLayout {
            vertical-stretch: 1;
            spacing: 0px;
            MaterialSidebar {
                tab <=> root.tab;
            }

            Rectangle {
                horizontal-stretch: 1;
                VerticalLayout {
                    padding: 16px;
                    spacing: 8px;

                    list := ScrollView {
                        horizontal-scrollbar-policy: always-off;
                        VerticalLayout {
                            for item[i] in root.tab.materials: VerticalLayout {
                                padding-bottom: 4px;
                                MaterialRow {
                                    width: list.visible-width;
                                    item: item;
                                }

                                if i < root.tab.materials.length - 1: Rectangle {
                                    border-width: 1px;
                                    height: 1px;
                                    border-color: UiState.theme.background-700;
                                }
                            }
                        }
                    }
                }
            }
        }

        Rectangle {
            height: 32px;
            background: {
                let c = UiState.theme.background-800.to-oklch();
                oklch(c.lightness - 0.05, c.chroma, c.hue, c.alpha);
            }
            path := ScrollView {
                horizontal-scrollbar-policy: always-off;
                vertical-scrollbar-policy: always-off;
                HorizontalLayout {
                    padding-left: 12px;
                    padding-right: 12px;
                    spacing: 8px;
                    alignment: start;
                    MaterialBreadcrumb {
                        title: "Courses";
                        course: true;
                        activated => { UiState.screen = Screen.courses; }
                    }

                    for item in root.tab.breadcrumbs: HorizontalLayout {
                        spacing: 8px;
                        Text {
                            text: "›";
                            color: UiState.theme.text-200;
                            vertical-alignment: center;
                        }

                        MaterialBreadcrumb {
                            title: item.title;
                            course: item.kind == "course";
                            activated => { CoursesUi.navigate-folder(item.course-id, item.id); }
                        }
                    }
                }
            }
        }
    }
}
