import { ScrollView } from "std-widgets.slint";
import { Screen } from "screens.slint";
import { MaterialRow } from "../components/material-row.slint";
import { MaterialItem, CourseTab } from "../types/course-ui.slint";
import { MaterialBreadcrumb } from "../components/material-breadcrumb.slint";
import { MaterialSidebar } from "../components/course-sidebar.slint";
import { UiState, CoursesUi } from "../globals.slint";
import { Theme } from "../palette.slint";
import { MaterialBottomBar } from "../components/material-bottom-bar.slint";

export component Materials inherits Rectangle {
    in property <CourseTab> tab;
    VerticalLayout {
        spacing: 0px;
        HorizontalLayout {
            vertical-stretch: 1;
            spacing: 0px;
            MaterialSidebar {
                tab <=> root.tab;
            }

            Rectangle {
                horizontal-stretch: 1;
                VerticalLayout {
                    padding: 16px;
                    spacing: 8px;

                    list := ScrollView {
                        horizontal-scrollbar-policy: always-off;
                        VerticalLayout {
                            for item[i] in root.tab.materials: VerticalLayout {
                                padding-bottom: 4px;
                                MaterialRow {
                                    width: list.visible-width;
                                    item: item;
                                }

                                if i < root.tab.materials.length - 1: Rectangle {
                                    border-width: 1px;
                                    height: 1px;
                                    border-color: UiState.theme.background-700;
                                }
                            }
                        }
                    }
                }
            }
        }

        MaterialBottomBar {
            tab <=> root.tab;
        }
    }
}
