import { Theme } from "../palette.slint";
import {
    ScrollView,
    HorizontalBox,
    VerticalBox,
    ListView,
} from "std-widgets.slint";
import { UiState } from "../ui-state.slint";

export component Notifications inherits Rectangle {
    background: UiState.theme.background-800;

    VerticalBox {
        ListView {
            for notif in UiState.notif.notifications: Rectangle {
                height: inner.height + 10px;
                inner := Rectangle {
                    border-radius: 5px;
                    border-width: 2px;
                    height: min(120px, max(30px, self.preferred-height));
                    border-color: UiState.theme.background-400;
                    background: UiState.theme.background-700;

                    preferred-height: title.preferred-height + course.preferred-height
                        + content.padding-top + content.padding-bottom + 16px;
                    clip: true;

                    HorizontalBox {

                        content := VerticalBox {
                            spacing: 2px;
                            title := Text {
                                text: notif.title;
                                font-weight: 700;
                                wrap: word-wrap;
                            }

                            course := Text {
                                color: UiState.theme.text-400;
                                text: notif.course;
                                wrap: word-wrap;
                            }
                        }
                    }
                }
            }
        }
    }
}
