[package]
name = "foam"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
slint = { version = "1.16.1", features = ["unstable-winit-030"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
dirs = "6"
reqwest = { version = "0.12", default-features = false, features = ["blocking", "json", "rustls-tls", "cookies"] }
chrono = { version = "0.4", features = ["serde"] }
chrono-tz = "0.10"
ical = "0.11"
regex = "1"
oauth = { version = "0.6", package = "oauth1-request" }
log = "0.4"
env_logger = "0.11"
derivative = "2.2.0"
scraper = "0.27.0"
itertools = "0.15.0"
rusqlite = "0.40.2"
serde_rusqlite = "0.43.0"
serde_with = { version = "3", features = ["json", "chrono_0_4"] }

[build-dependencies]
slint-build = "1.16.1"

[profile.release]
codegen-units = 1
lto = true

[target.'cfg(target_os = "macos")'.dependencies]
objc2 = "0.5"
objc2-app-kit = { version = "0.2", features = ["NSApplication", "NSResponder", "NSMenu", "NSMenuItem"] }
objc2-foundation = "0.2"
