import { Button, Slider, ScrollView } from "std-widgets.slint";
import { UiState, SettingsUi } from "../../globals.slint";
import { ScreenTopBar } from "../screen-top-bar.slint";
import { BottomBarFrame } from "../bottom-bar-frame.slint";

export component Settings inherits Rectangle {
    in property <length> sidebar-width;
    in property <bool> custom-titlebar;
    VerticalLayout {
        spacing: 0rem;
        ScreenTopBar {
            title: "Settings";
            icon: @image-url("../../icons/settings.svg");
            custom-titlebar: root.custom-titlebar;
        }

        Rectangle {
            vertical-stretch: 1;
            ScrollView {
                x: root.sidebar-width;
                width: parent.width - root.sidebar-width;
                height: parent.height;
                horizontal-scrollbar-policy: always-off;
                VerticalLayout {
                    padding: 1.5rem;
                    spacing: 1rem;
                    alignment: start;
                    Text {
                        text: "currently empty...";
                        font-size: 1.25rem;
                        color: UiState.theme.text-400;
                    }
                }
            }
        }

        BottomBarFrame { }
    }
}
