import { ScrollView } from "std-widgets.slint";
import { Breadcrumb } from "breadcrumb.slint";
import { UiState, CoursesUi } from "../../globals.slint";
import { Screen } from "../../types/screen.slint";
import { CourseTab } from "../../types/course-ui.slint";

export component BottomBar inherits Rectangle {
    in property <CourseTab> tab;

    path := ScrollView {
        horizontal-scrollbar-policy: always-off;
        vertical-scrollbar-policy: always-off;
        HorizontalLayout {
            padding-left: 12px;
            padding-right: 12px;
            spacing: 8px;
            alignment: start;
            Breadcrumb {
                title: "Courses";
                kind: "course";
                activated => { UiState.screen = Screen.courses; }
            }

            for item in root.tab.breadcrumbs: HorizontalLayout {
                spacing: 8px;
                Text {
                    text: "›";
                    color: UiState.theme.text-200;
                    vertical-alignment: center;
                }

                Breadcrumb {
                    title: item.title;
                    kind: item.kind;
                    activated => {
                        if item.kind == "folder" {
                            CoursesUi.navigate-folder(item.course-id, item.id);
                        }
                        if item.kind == "assignment" {
                            CoursesUi.navigate-assignment(item.course-id, item.id);
                        }
                    }
                }
            }
        }
    }
}
