import { UiState } from "../../globals.slint";
import { Icon } from "icon.slint";
import { HoverableButton } from "../hoverable-button.slint";

export component Breadcrumb inherits Rectangle {
    in property <string> title;
    in property <string> kind;
    callback activated();
    height: UiState.top-bar-height;
    background: action.has-hover || action.has-focus ? UiState.theme.background-700 : transparent;
    border-radius: 0.25rem;
    accessible-role: button;
    accessible-label: title;
    HorizontalLayout {
        spacing: 0.375rem;
        alignment: center;
        VerticalLayout {
            alignment: center;
            Icon {
                width: 0.875rem;
                height: 0.875rem;
                kind: root.kind;
            }
        }

        Text {
            text: root.title;
            color: UiState.theme.text-200;
            font-size: 0.75rem;
            vertical-alignment: center;
        }
    }

    action := HoverableButton {
        text: root.title;
        clicked => { root.activated(); }
    }
}
