import { ScrollView } from "std-widgets.slint";
import { Screen } from "../../types/screen.slint";
import { Row } from "row.slint";
import { MaterialItem, CourseTab } from "../../types/course-ui.slint";
import {
    Breadcrumb,
} from "breadcrumb.slint";
import { Sidebar } from "sidebar.slint";
import { UiState, CoursesUi } from "../../globals.slint";
import { Theme } from "../../palette.slint";

export component Materials inherits Rectangle {
    in property <CourseTab> tab;
    VerticalLayout {
        spacing: 0px;
        HorizontalLayout {
            vertical-stretch: 1;
            spacing: 0px;
            Sidebar {
                tab <=> root.tab;
            }

            Rectangle {
                horizontal-stretch: 1;
                VerticalLayout {
                    padding: 16px;
                    spacing: 8px;

                    list := ScrollView {
                        horizontal-scrollbar-policy: always-off;
                        VerticalLayout {
                            for item[i] in root.tab.materials: VerticalLayout {
                                padding-bottom: 4px;
                                Row {
                                    width: list.visible-width;
                                    item: item;
                                }

                                if i < root.tab.materials.length - 1: Rectangle {
                                    border-width: 1px;
                                    height: 1px;
                                    border-color: UiState.theme.background-700;
                                }
                            }
                        }
                    }
                }
            }
        }

    }
}
