import { ScrollView } from "std-widgets.slint";
import { Screen } from "../../types/screen.slint";
import { Row } from "row.slint";
import { MaterialItem, CourseTab } from "../../types/course-ui.slint";
import {
    Breadcrumb,
} from "breadcrumb.slint";
import { Sidebar } from "sidebar.slint";
import { UiState, CoursesUi } from "../../globals.slint";
import { Theme } from "../../palette.slint";
import { TopBar } from "top-bar.slint";
import { BottomBarFrame } from "../bottom-bar-frame.slint";

import { ScreenMenuItem } from "../../types/screen-menu-item.slint";

export global MaterialsMenu {
    out property <[ScreenMenuItem]> items: [
        {
            title: "Close tab",
            shortcut: @keys(Control + W),
            enabled: CoursesUi.active-tab >= 0 && CoursesUi.active-tab < CoursesUi.tabs.length
        },
    ];
    public function activate(index: int) {
        if index == 0 { CoursesUi.close-tab(CoursesUi.active-tab); }
    }
}

export component Materials inherits Rectangle {
    in property <length> sidebar-width: 0rem;
    in property <bool> custom-titlebar: false;
    in property <CourseTab> tab;
    VerticalLayout {
        spacing: 0rem;
        TopBar {
            tab: root.tab;
            custom-titlebar: root.custom-titlebar;
        }

        Rectangle {
            vertical-stretch: 1;
            Rectangle {
                x: root.sidebar-width;
                width: parent.width - root.sidebar-width;
                height: parent.height;
                HorizontalLayout {
                    spacing: 0rem;
                    Sidebar {
                        tab <=> root.tab;
                    }

                    Rectangle {
                        horizontal-stretch: 1;
                        list := ScrollView {
                            horizontal-scrollbar-policy: always-off;
                            VerticalLayout {
                                padding: 1rem;
                                for item[i] in root.tab.materials: VerticalLayout {
                                    padding-bottom: 0.25rem;
                                    Row {
                                        width: list.visible-width;
                                        item: item;
                                    }

                                    if i < root.tab.materials.length - 1: Rectangle {
                                        border-width: 0.0625rem;
                                        height: 0.0625rem;
                                        border-color: UiState.theme.background-700;
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }

        BottomBarFrame { }
    }
}
