import {
    CoursesUi,
    UiState,
    DocumentUi,
    AssignmentUi,
} from "../../globals.slint";
import { MaterialItem, CourseTab } from "../../types/course-ui.slint";
import { Icon } from "icon.slint";
import { HoverableButton } from "../hoverable-button.slint";

export component Row inherits Rectangle {
    in property <MaterialItem> item;
    in property <bool> selected;
    in property <float> tint;

    private property <bool> navigable: item.kind == "folder" || item.kind == "course";
    height: 2.5rem;
    border-radius: 0.3125rem;
    background: (selected ? UiState.theme.background-600
        : action.has-hover || action.has-focus ? UiState.theme.background-700 : transparent);
    HorizontalLayout {
        padding-left: 0.75rem;
        padding-right: 0.75rem;
        spacing: 0.625rem;
        VerticalLayout {
            alignment: center;
            Icon {
                width: 1.25rem;
                height: 1.25rem;
                kind: item.kind;
            }
        }

        Text {
            text: item.title;
            color: UiState.theme.text-50;
            vertical-alignment: center;
            overflow: elide;
            font-size: 1.125rem;
            horizontal-stretch: 1;
        }

        Text {
            font-size: 0.75rem;
            text: root.navigable ? "›" : "";
            color: UiState.theme.text-200;
            vertical-alignment: center;
        }
    }

    action := HoverableButton {
        text: item.title;
        clicked => {
            if root.navigable {
                CoursesUi.open-folder(item.course-id, item.id);
            }
            if item.kind == "assignment" {
                AssignmentUi.open(item.course-id, item.id);
            }
            if item.kind == "document" { DocumentUi.open(item.course-id, item.id); }
        }
    }
}
