import { ScrollView } from "std-widgets.slint";
import { Row } from "row.slint";
import { CoursesUi, UiState } from "../../globals.slint";
import { CourseTab, MaterialItem } from "../../types/course-ui.slint";

export component Sidebar inherits Rectangle {
    in property <CourseTab> tab;
    in property <[MaterialItem]> items: tab.parent-materials;
    in property <string> selected-id: tab.folder-id;

    width: 12.5rem;
    background: {
        let c = UiState.theme.background-800.to-oklch();
        oklch(c.lightness - 0.03, c.chroma, c.hue, c.alpha)
    };
    sidebar := ScrollView {
        horizontal-scrollbar-policy: always-off;
        VerticalLayout {
            spacing: 0.1245rem;

            padding-top: 1rem;
            padding-bottom: 1rem;
            padding-left: 0.5rem;
            padding-right: 0.5rem;

            for item[i] in root.items: VerticalLayout {
                padding-bottom: 0.1245rem;
                Row {
                    width: sidebar.visible-width;
                    item: item;
                    selected: item.course-id == root.tab.course-id
                        && (item.kind == "course" || item.id == root.selected-id);
                }
            }
        }
    }
}
