import { ScrollView } from "std-widgets.slint";
import { Breadcrumb } from "breadcrumb.slint";
import { UiState, CoursesUi, DocumentUi } from "../../globals.slint";
import { Screen } from "../../types/screen.slint";
import { CourseTab } from "../../types/course-ui.slint";
import { TopBarFrame } from "../top-bar-frame.slint";

export component TopBar inherits TopBarFrame {
    in property <CourseTab> tab;

    path := ScrollView {
        horizontal-scrollbar-policy: always-off;
        vertical-scrollbar-policy: always-off;
        HorizontalLayout {
            padding-left: 0.75rem;
            padding-right: 0.75rem;
            spacing: 0.5rem;
            alignment: start;
            Breadcrumb {
                title: "Courses";
                kind: "course";
                activated => { UiState.screen = Screen.courses; }
            }

            for item in root.tab.breadcrumbs: HorizontalLayout {
                spacing: 0.5rem;
                alignment: start;
                horizontal-stretch: 0;
                Image {
                    width: 0.75rem;
                    y: 0.625rem;
                    source: @image-url("../../icons/chevron-right.svg");
                    colorize: UiState.theme.text-200;
                    vertical-alignment: top;
                }

                Breadcrumb {
                    title: item.title;
                    kind: item.kind;
                    activated => {
                        if item.kind == "course" {
                            CoursesUi.navigate-course(item.course-id);
                            CoursesUi.navigate-folder(item.course-id, "");
                        }
                        if item.kind == "folder" {
                            CoursesUi.navigate-folder(item.course-id, item.id);
                        }
                        if item.kind == "assignment" {
                            CoursesUi.navigate-assignment(item.course-id, item.id);
                        }
                        if item.kind == "document" {
                            DocumentUi.open(item.course-id, item.id);
                        }
                    }
                }
            }
        }
    }
}
