import { ScrollView, VerticalBox, Button } from "std-widgets.slint";
import { AssignmentUi, CoursesUi, UiState } from "../../globals.slint";
import { CourseTab } from "../../types/course-ui.slint";
import { Sidebar } from "../materials/sidebar.slint";
import {
    Breadcrumb,
} from "../materials/breadcrumb.slint";
import { Screen } from "../../types/screen.slint";
import { SelectableText } from "../selectable-text.slint";
import { TopBar } from "../materials/top-bar.slint";
import { AssignmentBottomBar } from "bottom-bar.slint";

import { ScreenMenuItem } from "../../types/screen-menu-item.slint";
import { HoverableButton } from "../hoverable-button.slint";

export global AssignmentMenu {
    out property <[ScreenMenuItem]> items: [
        {
            title: "Close tab",
            shortcut: @keys(Control + W),
            enabled: CoursesUi.active-tab >= 0 && CoursesUi.active-tab < CoursesUi.tabs.length
        },
        {
            title: "View attachments",
            shortcut: @keys(A),
            enabled: AssignmentUi.assignment.attachments.length > 0
        },
        {
            title: "Open in browser",
            shortcut: @keys(O),
            enabled: !AssignmentUi.assignment.id.is-empty
        },
        {
            title: "View submissions",
            shortcut: @keys(S),
            enabled: AssignmentUi.assignment.submission-file-count > 0
        },
    ];
    public function activate(index: int) {
        if index == 0 { CoursesUi.close-tab(CoursesUi.active-tab); }
        else if index == 1 { AssignmentUi.view-attachments(0); }
        else if index == 2 { AssignmentUi.open-browser(); }
        else if index == 3 { AssignmentUi.view-submissions(0); }
    }
}

export component AssignmentView inherits Rectangle {
    in property <length> sidebar-width: 0rem;
    in property <bool> custom-titlebar: false;
    in property <CourseTab> tab;
    background: UiState.theme.background-800;

    VerticalLayout {
        spacing: 0rem;
        TopBar {
            tab: root.tab;
            custom-titlebar: root.custom-titlebar;
        }

        Rectangle {
            vertical-stretch: 1;
            Rectangle {
                x: root.sidebar-width;
                width: parent.width - root.sidebar-width;
                height: parent.height;
                HorizontalLayout {
                    spacing: 0rem;
                    Sidebar {
                        tab: root.tab;
                        items: root.tab.materials;
                        selected-id: AssignmentUi.assignment.id;
                    }

                    Rectangle {
                        horizontal-stretch: 1;
                        VerticalLayout {
                            padding: 1rem;
                            spacing: 0.875rem;

                            VerticalLayout {
                                padding-left: 0.1245rem;
                                padding-top: 0.5rem;
                                spacing: 1rem;

                                SelectableText {
                                    text: AssignmentUi.assignment.title;
                                    font-size: 1.5rem;
                                    font-weight: 700;
                                    color: UiState.theme.text-50;
                                }

                                if !AssignmentUi.error.is-empty: SelectableText {
                                    text: AssignmentUi.error;
                                    color: UiState.theme.primary-300;
                                    font-size: 1.125rem;
                                }

                                HorizontalLayout {
                                    padding-left: 0.1245rem;
                                    SelectableText {
                                        text: AssignmentUi.assignment.due + " • ID " + AssignmentUi.assignment.id;
                                        color: UiState.theme.text-200;
                                        font-size: 0.875rem;
                                    }

                                    Rectangle {
                                        horizontal-stretch: 1;
                                    }

                                    SelectableText {
                                        text: "Grade: " + AssignmentUi.assignment.grade;
                                        color: UiState.theme.text-200;
                                        font-size: 0.875rem;
                                    }
                                }
                            }

                            ScrollView {
                                horizontal-scrollbar-policy: always-off;
                                VerticalLayout {
                                    alignment: start;
                                    spacing: 0.75rem;
                                    padding-right: 0.75rem;
                                    if !AssignmentUi.assignment.description.is-empty: VerticalLayout {
                                        Rectangle {
                                            background: UiState.theme.background-750;
                                            border-radius: 0.5rem;
                                            height: description-content.preferred-height;

                                            description-content := VerticalLayout {
                                                padding: 0.75rem;
                                                SelectableText {
                                                    text: AssignmentUi.assignment.description;
                                                    color: UiState.theme.text-100;
                                                    font-size: 1rem;
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }

                    Rectangle {
                        width: 12.5rem;
                        background: {
                            let c = UiState.theme.background-800.to-oklch();
                            oklch(c.lightness - 0.02, c.chroma, c.hue, c.alpha)
                        };
                        VerticalLayout {
                            spacing: 1.5rem;
                            VerticalLayout {
                                padding: 1rem;
                                spacing: 0.75rem;
                                SelectableText {
                                    text: "Attachments";
                                    font-size: 1.125rem;
                                    font-weight: 700;
                                    color: UiState.theme.text-50;
                                }

                                if AssignmentUi.assignment.attachments.length > 0: VerticalLayout {
                                    spacing: 0.375rem;

                                    for file[index] in AssignmentUi.assignment.attachments: att-btn := HoverableButton {
                                        clicked => { AssignmentUi.view-attachments(index); }
                                        Rectangle {
                                            background: att-btn.has-hover ? UiState.theme.background-700 : UiState.theme.background-750;
                                            border-radius: 0.3125rem;
                                            VerticalLayout {
                                                padding: 0.5rem;
                                                Text {
                                                    font-size: 0.75rem;
                                                    text: file.title;
                                                    color: UiState.theme.text-100;
                                                }

                                                if !file.details.is-empty: Text {
                                                    font-size: 0.75rem;
                                                    text: file.details;
                                                    color: UiState.theme.text-400;
                                                }
                                            }
                                        }
                                    }
                                }

                                if AssignmentUi.assignment.attachments.length == 0: SelectableText {
                                    text: "No attachments";
                                    color: UiState.theme.text-400;
                                    font-size: 0.875rem;
                                }
                            }

                            VerticalLayout {
                                padding: 1rem;
                                spacing: 0.75rem;
                                SelectableText {
                                    text: "Submissions";
                                    font-size: 1.125rem;
                                    font-weight: 700;
                                    color: UiState.theme.text-50;
                                }

                                if AssignmentUi.assignment.submissions.length == 0: SelectableText {
                                    text: "No submissions yet";
                                    color: UiState.theme.text-400;
                                    font-size: 0.875rem;
                                }

                                ScrollView {
                                    horizontal-scrollbar-policy: always-off;
                                    VerticalLayout {
                                        alignment: start;
                                        spacing: 0.625rem;
                                        padding-right: 0.5rem;
                                        if AssignmentUi.assignment.submissions.length > 0: VerticalLayout {
                                            spacing: 0.625rem;

                                            for submission[index] in AssignmentUi.assignment.submissions: sub-btn := HoverableButton {
                                                enabled: submission.files.length > 0;
                                                clicked => { AssignmentUi.view-submissions(index); }
                                                height: content.preferred-height + 1.25rem;
                                                Rectangle {
                                                    background: sub-btn.has-hover ? UiState.theme.background-700 : UiState.theme.background-750;
                                                    border-radius: 0.375rem;
                                                    height: parent.height;
                                                    content := VerticalLayout {
                                                        padding: 0.625rem;
                                                        Text {
                                                            text: "Revision " + submission.id;
                                                            color: UiState.theme.text-100;
                                                            font-size: 0.875rem;
                                                        }

                                                        Text {
                                                            font-size: 0.75rem;
                                                            text: submission.created-at + " · " + submission.status;
                                                            color: UiState.theme.text-300;
                                                        }

                                                        if !submission.body.is-empty: SelectableText {
                                                            text: submission.body;
                                                            color: UiState.theme.text-100;
                                                        }
                                                        for file in submission.files: VerticalLayout {
                                                            Text {
                                                                font-size: 0.75rem;
                                                                text: file.title;
                                                                color: UiState.theme.text-100;
                                                            }

                                                            if !file.details.is-empty: Text {
                                                                font-size: 0.75rem;
                                                                text: file.details;
                                                                color: UiState.theme.text-400;
                                                            }
                                                        }
                                                    }
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }

        AssignmentBottomBar { }
    }
}
