export struct AssignmentFile { title: string, details: string, url: string }

export struct SubmissionRow {
    id: string,
    user-id: string,
    created-at: string,
    status: string,
    body: string,
    files: [AssignmentFile],
}

export struct AssignmentWithDetails {
    id: string,
    title: string,
    course-id: string,
    course-name: string,
    due: string,
    description: string,
    completion: string,
    grade: string,
    submission-policy: bool,
    attachments: [AssignmentFile],
    submissions: [SubmissionRow],
}
