export struct CourseItem {
    id: string,
    title: string,
    section: string,
    code: string,
    period: string,
    hidden: bool,
    icon: image,
}

export struct MaterialItem {
    course-id: string,
    id: string,
    title: string,
    kind: string,
}

export struct CourseTab {
    breadcrumbs: [MaterialItem],
    course-id: string,
    title: string,
    image: image,
    folder-id: string,
    assignment-id: string,
    folder-title: string,
    parent-title: string,
    browser-error: string,
    materials: [MaterialItem],
    parent-materials: [MaterialItem],
}
