import { HorizontalBox } from "std-widgets.slint";
import { Dashboard } from "screen/dashboard.slint";
import { Screen } from "screen/screens.slint";
import { Courses } from "screen/courses.slint";
import { Sidebar } from "components/sidebar.slint";
import { UiState } from "globals.slint";
export { UiState, DashboardUi, NotificationUi, CoursesUi } from "globals.slint";
import "./fonts/MozillaText.ttf";
import { Notifications } from "screen/notifications.slint";

export component AppWindow inherits Window {
    title: "Foam";
    default-font-family: "Mozilla Text";
    preferred-width: 1100px;
    preferred-height: 700px;

    background: UiState.theme.background-800;

    HorizontalBox {
        padding: 0px;
        spacing: 0px;

        Sidebar { }

        Rectangle {
            horizontal-stretch: 1;
            vertical-stretch: 1;
            if UiState.screen == Screen.dashboard: Dashboard {
                width: parent.width;
                height: parent.height;
            }

            if UiState.screen == Screen.notifs: Notifications {
                width: parent.width;
                height: parent.height;
            }

            if UiState.screen == Screen.courses: Courses {
                width: parent.width;
                height: parent.height;
            }
        }
    }
}
