import { HorizontalBox, VerticalBox } from "std-widgets.slint";
import { Theme } from "palette.slint";
import { AssignmentCol } from "types/assignment.slint";

export component Dashboard inherits Rectangle {
    background: Theme.dark.background-800;
    padding: 32px;

    in-out property <[AssignmentCol]> assignment-view;

    HorizontalBox {
        for col in assignment-view: VerticalBox {
            Text {
                text: col.title;
                color: Theme.dark.text-400;
            }

            for assignment in col.assignments: Rectangle {
                background: col.color;
                Text {
                    text: assignment.title;
                }
            }
        }
    }
}
