import { Screen } from "screen/screens.slint";
import { Theme, ColorPalette } from "palette.slint";
import { Assignment, AssignmentCol } from "types/dashboard-ui.slint";
import { Notification } from "types/notification-ui.slint";
import { CourseItem, MaterialItem } from "types/course-ui.slint";

export global UiState {
    in-out property <Screen> screen: Screen.dashboard;
    in-out property <ColorPalette> theme: Theme.dark;
}

export global DashboardUi {
    in-out property <[AssignmentCol]> assignment-view;
    in-out property <Assignment> selected-assignment;
    in-out property <int> sel-row;
    in-out property <int> sel-col;
    callback view-item();
    callback set-done(bool, string);
}

export global NotificationUi {
    in-out property <float> progress;
    in-out property <[Notification]> temp-notifs;
    in-out property <[Notification]> notifications;
}

export global CoursesUi {
    in-out property <string> course-id;
    in-out property <string> folder-id;
    in-out property <string> folder-title: "Courses";
    in-out property <string> parent-title: "Courses";
    in-out property <string> browser-error;
    in-out property <[MaterialItem]> materials;
    in-out property <[MaterialItem]> parent-materials;
    callback open(string, string, string);
    callback up();
    in-out property <[CourseItem]> courses;
    callback reorder(int, int);
    callback hide(string);
    pure callback drag-data(int) -> data-transfer;
    pure callback drag-index(data-transfer) -> int;
}
