import { Screen } from "types/screen.slint";
import { Theme, ColorPalette } from "palette.slint";
import { Assignment, AssignmentCol } from "types/dashboard-ui.slint";
import { Notification, NotificationType } from "types/notification-ui.slint";
import { CourseItem, MaterialItem, CourseTab } from "types/course-ui.slint";
import { AssignmentWithDetails } from "types/assignment-ui.slint";

export global UiState {
    in-out property <length> font-size;
    in-out property <bool> shift-held: false;
    in-out property <string> shortcut-modifier: "Ctrl";
    in-out property <int> focused-sidebar-item: -1;
    in-out property <Screen> screen: Screen.dashboard;
    in-out property <ColorPalette> theme: Theme.dark;
    out property <length> top-bar-height: font-size * 2;
    out property <length> bottom-bar-height: font-size * 1.75;
}

export global SettingsUi {
    in-out property <int> font-size: 16;
    in-out property <string> save-error;
    callback set-font-size(int);
}

export global DashboardUi {
    in-out property <[AssignmentCol]> assignment-view;
    in-out property <Assignment> selected-assignment;
    in-out property <int> sel-row;
    in-out property <int> sel-col;
    callback view-item();
    callback set-done(bool, string);
    public function open-selected() {
        AssignmentUi.open(selected-assignment.course-id, selected-assignment.id);
    }
    public function toggle-selected-done() {
        assignment-view[sel-col].assignments[sel-row].done = !selected-assignment.done;
        selected-assignment = assignment-view[sel-col].assignments[sel-row];
        set-done(selected-assignment.done, selected-assignment.id);
    }
    public function unselect() {
        selected-assignment = { };
    }
}

export global NotificationUi {
    in-out property <Notification> selected-notification;
    out property <bool> can-open-selected: !selected-notification.course-id.is-empty
        && !selected-notification.resource-id.is-empty
        && (selected-notification.n-type == NotificationType.new-assignment
            || selected-notification.n-type == NotificationType.new-grade
            || selected-notification.n-type == NotificationType.new-document);
    public function open-selected() {
        if can-open-selected {
            if selected-notification.n-type == NotificationType.new-document {
                DocumentUi.open(selected-notification.course-id, selected-notification.resource-id);
            } else {
                AssignmentUi.open(selected-notification.course-id, selected-notification.resource-id);
            }
        }
    }
    public function toggle-selected-read() {
        if !selected-notification.id.is-empty {
            set-read(selected-notification.id, selected-notification.unread);
        }
    }
    public function unselect() { selected-notification = { }; }
    in-out property <int> unread-count;
    callback opened();
    callback closed();
    callback set-read(string, bool);
    in-out property <float> progress;
    in-out property <[Notification]> temp-notifs;
    in-out property <[Notification]> notifications;
}

export global CoursesUi {
    in-out property <bool> show-hidden: false;
    in-out property <[CourseTab]> tabs;
    in-out property <int> active-tab: -1;
    callback select-tab(int);
    callback close-tab(int);
    in-out property <string> course-id;
    in-out property <string> folder-id;
    in-out property <string> folder-title: "Courses";
    in-out property <string> parent-title: "Courses";
    in-out property <string> browser-error;
    in-out property <[MaterialItem]> materials;
    in-out property <[MaterialItem]> parent-materials;
    callback navigate-course(string);
    callback navigate-course-with-image(string, image);
    callback navigate-folder(string, string);
    callback navigate-assignment(string, string);
    in-out property <[CourseItem]> courses;
    in-out property <int> period-character-count: 1;
    callback reorder(int, int);
    callback toggle-hidden(string);
    callback set-period(string, string) -> string;
    pure callback drag-data(int) -> data-transfer;
    pure callback drag-index(data-transfer) -> int;
}

export global AssignmentUi {
    in-out property <AssignmentWithDetails> assignment;
    in-out property <string> error;
    callback open(string, string);
    callback view-attachments(int);
    callback view-submissions(int);
    callback open-browser();
}

export global DocumentUi {
    in-out property <string> id;
    in-out property <string> title;
    in-out property <string> error;
    callback open(string, string);
}
