import { Screen } from "types/screen.slint";
import { Theme, ColorPalette } from "palette.slint";
import { Assignment, AssignmentCol } from "types/dashboard-ui.slint";
import { Notification } from "types/notification-ui.slint";
import { CourseItem, MaterialItem, CourseTab } from "types/course-ui.slint";
import { AssignmentWithDetails } from "types/assignment-ui.slint";

export global UiState {
    in-out property <Screen> screen: Screen.dashboard;
    in-out property <ColorPalette> theme: Theme.dark;
}

export global DashboardUi {
    in-out property <[AssignmentCol]> assignment-view;
    in-out property <Assignment> selected-assignment;
    in-out property <int> sel-row;
    in-out property <int> sel-col;
    callback view-item();
    callback set-done(bool, string);
    public function open-selected() {
        AssignmentUi.open(selected-assignment.course-id, selected-assignment.id);
    }
    public function toggle-selected-done() {
        assignment-view[sel-col].assignments[sel-row].done = !selected-assignment.done;
        selected-assignment = assignment-view[sel-col].assignments[sel-row];
        set-done(selected-assignment.done, selected-assignment.id);
    }
    public function unselect() {
        selected-assignment = { };
    }
}

export global NotificationUi {
    in-out property <float> progress;
    in-out property <[Notification]> temp-notifs;
    in-out property <[Notification]> notifications;
}

export global CoursesUi {
    in-out property <bool> show-hidden: false;
    in-out property <[CourseTab]> tabs;
    in-out property <int> active-tab: -1;
    callback select-tab(int);
    in-out property <string> course-id;
    in-out property <string> folder-id;
    in-out property <string> folder-title: "Courses";
    in-out property <string> parent-title: "Courses";
    in-out property <string> browser-error;
    in-out property <[MaterialItem]> materials;
    in-out property <[MaterialItem]> parent-materials;
    callback activate-course(string);
    callback navigate-folder(string, string);
    callback navigate-assignment(string, string);
    in-out property <[CourseItem]> courses;
    in-out property <int> period-character-count: 1;
    callback reorder(int, int);
    callback toggle-hidden(string);
    callback set-period(string, string) -> string;
    pure callback drag-data(int) -> data-transfer;
    pure callback drag-index(data-transfer) -> int;
}

export global AssignmentUi {
    in-out property <AssignmentWithDetails> assignment;
    in-out property <string> error;
    callback open(string, string);
}
