import { Button, VerticalBox } from "std-widgets.slint";
import { Theme } from "palette.slint";

export component Home inherits Window {
    preferred-width: 1200px;
    preferred-height: 800px;

    in-out property <color> text-color: Theme.dark.text-50;
    in-out property <color> background-color: Theme.dark.background-800;
    in-out property <color> primary-color: Theme.dark.primary-500;

    background: root.background-color;

    VerticalBox { }
}
