import { VerticalBox } from "std-widgets.slint";
import { Theme } from "palette.slint";

component NavigationItem inherits Rectangle {
    in property <string> label;
    in property <image> icon;
    in property <bool> selected: false;

    height: 44px;
    border-radius: 6px;
    background: selected ? Theme.dark.background-700 : transparent;

    Image {
        source: icon;
        colorize: Theme.dark.text-200;
    }
    // Text {
    //     text: root.label;
    //     color: selected ? Theme.dark.text-50 : Theme.dark.text-200;
    //     font-size: 16px;
    //     vertical-alignment: center;
    //     x: 16px;
    // }
}

export component Sidebar inherits Rectangle {
    in property <bool> minimized: true;
    width: minimized ? 60px : 240px;
    background: Theme.dark.background-900;

    VerticalBox {
        padding: 8px;
        spacing: 10px;

        Rectangle {
            height: 0px;
        }

        NavigationItem {
            label: "Dashboard";
            selected: true;
            icon: @image-url("icons/calendar-days.svg");
        }

        Rectangle {
            vertical-stretch: 1;
        }

        NavigationItem {
            label: "Settings";
            icon: @image-url("icons/settings.svg");
        }
    }
}
