import { VerticalBox } from "std-widgets.slint";
import { ProgressRing } from "components/progress-ring.slint";
import { Theme } from "palette.slint";
import { Screen } from "screen/screens.slint";
import { UiState } from "ui-state.slint";

component NavigationItem inherits Rectangle {
    in property <string> label;
    in property <image> icon;

    in property <Screen> change-to;
    in property <float> progress: 0;

    height: 44px;
    border-radius: 6px;
    background: UiState.screen == change-to ? Theme.dark.background-700 : (touch.has-hover ? Theme.dark.background-600 : transparent);

    touch := TouchArea {
        clicked => {
            UiState.screen = change-to;
        }
    }

    if progress > 0: ProgressRing {
        progress: root.progress;
    }

    Image {
        source: icon;
        colorize: Theme.dark.text-200;
    }
    // Text {
    //     text: root.label;
    //     color: selected ? Theme.dark.text-50 : Theme.dark.text-200;
    //     font-size: 16px;
    //     vertical-alignment: center;
    //     x: 16px;
    // }
}

export component Sidebar inherits Rectangle {
    in property <bool> minimized: true;

    width: minimized ? 60px : 240px;
    background: Theme.dark.background-900;

    VerticalBox {
        padding: 8px;
        spacing: 10px;

        Rectangle {
            height: 0px;
        }

        NavigationItem {
            label: "Dashboard";
            icon: @image-url("icons/calendar-days.svg");
            change-to: dashboard;
        }

        NavigationItem {
            label: "Notifications";
            icon: @image-url("icons/bell.svg");
            progress: UiState.notif.progress;
            change-to: notifs;
        }

        Rectangle {
            vertical-stretch: 1;
        }

        NavigationItem {
            label: "Settings";
            icon: @image-url("icons/settings.svg");
            change-to: settings;
        }
    }
}
