// ui/ui-state.slint
import { Screen } from "screen/screens.slint";
import { DashboardUi } from "types/dashboard-ui.slint";
import { NotificationUi } from "types/notification-ui.slint";
import { Theme, ColorPalette } from "palette.slint";

export global UiState {
    in-out property <Screen> screen: Screen.dashboard;
    in-out property <DashboardUi> dashboard;
    in-out property <NotificationUi> notif;
    in-out property <ColorPalette> theme: Theme.dark;
}
