name: Package

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  package:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-latest
            target: aarch64-apple-darwin

          - os: macos-15-intel
            target: x86_64-apple-darwin

          - os: windows-latest
            target: x86_64-pc-windows-msvc

          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v6

      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Install cargo-packager
        run: cargo install cargo-packager --locked

      - name: Package
        run: cargo packager --release --target ${{ matrix.target }}

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          prerelease: ${{ contains(github.ref_name, '-') }}
          files: |
            target/release/bundle/**/*
